### ISSUE TITLE
Add Dependabot

### ISSUE THREAD

**Issue by DarkS0ul3** [science-computing/wartungsplan#4]
To keep the dependencies updated

**Comment by Jack28** [comment]
Yes, I agree.

I would vote to keep pinning the exact version.
What is your opinion on this?

Cheeky of you to directly assign the issue to me =D

**Comment by DarkS0ul3** [comment]
Like define which versions to use in the project (requirements.txt) and then update the version(s) if there is a newer version (information from dependabot and tested to avoid issues)?
